### ISSUE TITLE
Usage in frigate 

### ISSUE THREAD

**Issue by dipiex** [dbuezas/icsee-ptz#1]
Could you assist me?
I'm having trouble understanding how to use go2rtc with dvrip to retrieve images from an icsee camera without relying on onvif.

I have two PCs, one for frigate and another for hass. Both are running on docker-compose.
Should I install go2rtc on my docker alongside frigate?

I'm a little confused about the streaming  connection as well.
Will frigate be able to interpret this "dvrip://" link?
"dvrip://admin:my_cam_password@192.168.178.27:34567"

Thank you for your time

**Comment by dbuezas** [comment]
Frigate comes with go2rtc preinstalled. In your frigate.yaml add

```yaml
go2rtc:
  streams:
     my_cam: dvrip://admin:your_pass@192.168.x.x
```

Then in the frigate section you can use `my_cam` instead of a url

**Comment by dipiex** [comment]
Thank you so much, it works perfectly!

By the way, do you know how to obtain the sub stream?

**Comment by dbuezas** [comment]
Glad to hear! 🎉 

For rhe lower res stream Add `&subtype=1` to the dvrip url.
Here are the relevant go2rtc docs: https://github.com/AlexxIT/go2rtc#source-dvrip

**Comment by dbuezas** [comment]
Finding these should become easier once this PR is merged https://github.com/AlexxIT/go2rtc/pull/462

**Comment by dipiex** [comment]
Unfortunately, the substream didn't work on the provided URL with the ending "?channel=0&subtype=1".
It still shows the main stream.

**Comment by dbuezas** [comment]
You can also try channel=1, but i think it should be subtype
