### ISSUE TITLE
integration can"t create binary entity 

### ISSUE THREAD

**Issue by uowis** [dbuezas/icsee-ptz#10]
the connexion is good, but : 
```
Logger: homeassistant.components.binary_sensor
Source: custom_components/icsee_ptz/binary_sensor.py:62
Integration: Capteur binaire ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 07:24:11 (8 occurrences)
Last logged: 10:56:09

Error while setting up icsee_ptz platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/icsee_ptz/binary_sensor.py", line 49, in async_setup_entry
    [
  File "/config/custom_components/icsee_ptz/binary_sensor.py", line 50, in <listcomp>
    Alarm(hass, entry, channel)
  File "/config/custom_components/icsee_ptz/binary_sensor.py", line 62, in __init__
    assert self._attr_unique_id  # set by ICSeeEntity
AssertionError
```

**Comment by uowis** [comment]
![image](https://github.com/dbuezas/icsee-ptz/assets/1370666/60c33011-7231-4375-8bd3-bc45edb64ded)

**Comment by dbuezas** [comment]
Re-logins are on purpose, the keep alive function in the library doesn't work well, particularly while watching alarms. The integration actually logs in a new connection before login out the old one to avoid missing alarms

**Comment by dbuezas** [comment]
It seems like you have an issue with unique ids. Try removing and reading the camera, maybe something went wrong with the migration from the older version

**Comment by dbuezas** [comment]
Please try [v4.0.0](https://github.com/dbuezas/icsee-ptz/releases/tag/v4.0.0).
I'm sorry but you'll need to re-add all cameras yet again (I haven't fully wrapped my mind about migrations yet), but this is hopefully the last time this is necessary.

**Comment by dbuezas** [comment]
Oh I see. I'm still using the mac address to identify the device, so HA can add other entities that may come from the router (like internet access). In your case, the system fails to grab the mac address and that results in an undefined value used.

I'll add an extra check to not do that if the mac address is None.

**Comment by dbuezas** [comment]
By the way, isn't this also breaking other integrations? I took the pattern from integrations in the HA core.

**Comment by dbuezas** [comment]
Please give v4.0.1 a try and let me know

**Comment by sc16me** [comment]
> Please give v4.0.1 a try and let me know

Thank you! Everything seems to be working well now! There are no errors in HA-Corе. And I don't see any problems with other integrations either.

**Comment by dbuezas** [comment]
Yes! Success!

**Comment by uowis** [comment]
it's good for me too ! Congratulation
