### ISSUE TITLE
2 way audio

### ISSUE THREAD

**Issue by eerison** [dbuezas/icsee-ptz#16]
hey @dbuezas I know it does not make part of this project.

But did you make 2 way audio works using go2rtc? if yes do you have some example and how do you test it?

I mean, for ICsee cameras

**Comment by dbuezas** [comment]
I haven't, and I am curious about the same too :) I gave it a short try but didn't succeed.
If you find out, let me know!

**Comment by eerison** [comment]
Ok, in case I find something I reopen this issue ;)
