### ISSUE TITLE
My neighbour shares this camera with me

### ISSUE THREAD

**Issue by arne182** [dbuezas/icsee-ptz#24]
Is it possible to get this working over the online service? 
As it is not my camera I can not do much else.

**Comment by dbuezas** [comment]
You need to be in the same subnetwork (direct connection with the camera), this won't work via their cloud

**Comment by arne182** [comment]
So I could get him to let it run over my WiFi but now it is showing an unknown motion status
![Screenshot_20231209_135610_Home Assistant](https://github.com/dbuezas/icsee-ptz/assets/844102/6dab331e-cb7c-4d14-bedb-1800a72d52fb)

**Comment by dbuezas** [comment]
Try enabling movement alarms in the icsee app. Alternatively, enable experimental entities inside the CONFIGURE of the device in the integration page. This will add alarm toggles (use at own risk)

**Comment by arne182** [comment]
Just changed channel from 0 to 1 and now it is working

**Comment by dbuezas** [comment]
Congrats!
