### ISSUE TITLE
can't setup any DVR

### ISSUE THREAD

**Issue by Destroyer061090** [dbuezas/icsee-ptz#29]
Hello,

i have been able to install it but then this is what happen. any idea why?

![immagine](https://github.com/dbuezas/icsee-ptz/assets/126196958/95497035-4e7e-4439-85d2-48bff4ccaa7c)

**Comment by dbuezas** [comment]
Look in the logs, maybe the username or password aren't right

**Comment by Destroyer061090** [comment]
But it never appear this page:
<img width="447" alt="IMG_3123" src="https://github.com/dbuezas/icsee-ptz/assets/126196958/59bf5c65-aff1-496f-a2a4-2db3ec888b09">

**Comment by dbuezas** [comment]
That's odd... Have you tried ~turning it on and off again~ restarting?
