### ISSUE TITLE
White Light control

### ISSUE THREAD

**Issue by felpsnew** [dbuezas/icsee-ptz#31]
Is it possible to control the white light on this camera?

![Imagem do WhatsApp de 2024-01-05 à(s) 12 01 24_10e175a2](https://github.com/dbuezas/icsee-ptz/assets/55771746/cc4f0208-1cda-45b3-b5b8-05356438794c)
![Imagem do WhatsApp de 2024-01-04 à(s) 10 27 28_35ae8a89](https://github.com/dbuezas/icsee-ptz/assets/55771746/8f219988-85a1-4018-a0e4-ce11956559f3)

The select.*_white_light entity is not being made available.

![image](https://github.com/dbuezas/icsee-ptz/assets/55771746/d2bad1cd-78de-4462-9c96-9abed32f6564)

![image](https://github.com/dbuezas/icsee-ptz/assets/55771746/1223f32e-3950-4f28-be56-ed9a9143445d)

Would it be possible to turn on the camera's white light?

**Comment by dbuezas** [comment]
Try the latest release. It was a pre release and I just marked it as latest release. It includes a contribution related to that

**Comment by felpsnew** [comment]
Now the entity appears, but I can't manually control the white light, is it possible to control the white light?

![image](https://github.com/dbuezas/icsee-ptz/assets/55771746/d0d08301-c8a0-4f00-86dd-b47b6bbeb6ed)

**Comment by dbuezas** [comment]
Different cameras work differently, try changing the values of both "white light" and "day night color"

**Comment by felpsnew** [comment]
I used them all as combinations, I can only force night vision. Do you think it would be possible by editing the code to find a way to force the white light to turn on?

**Comment by dbuezas** [comment]
If it can be done with the icsee app then most likely. 
Try this: https://github.com/OpenIPC/python-dvr?tab=readme-ov-file#investigate-more-settings
