### ISSUE TITLE
ptz Stop not working

### ISSUE THREAD

**Issue by LucaCraft89** [dbuezas/icsee-ptz#34]
The problem it's  easy to understand, when i press the button in ha the capera moves but does not stop in anyway, and mannulay calling the stop service does not work, help me i have been going thru many configuartion panels and nothing works, i am going thru a dvr

**Comment by dbuezas** [comment]
Sorry to hear that. There's actually no specific stop command to stop the camera, so the integration sends does `await self.cam.dvrip.ptz("DirectionUp", preset=-1)`, which in most cameras does the trick. Try sending DirectionUp with other preset number, maybe some other works for your specific camera

**Comment by LucaCraft89** [comment]
Thanks, analyzing the calls from the website of the DVR it seems that the stop is preset -1, but I can't sand it thru home assistant, would you mind helping me figure out how to do that thru ha?

**Comment by dbuezas** [comment]
You can test it via Develoer Tools

![Screenshot_20240213-150002](https://github.com/dbuezas/icsee-ptz/assets/777196/c0fbb48a-3fdd-4ff5-960b-3aebbee44fa0)

**Comment by LucaCraft89** [comment]
I already tried it doesn't let me go below 0

**Comment by dbuezas** [comment]
Oh, you'll have to hack the code a bit then. 
* Inside your `custom_components` folder, you'll find this integration. (you can use the file editor addon [from here](http://homeassistant.local:8123/hassio/store))
* Then modify [this line of this file](https://github.com/dbuezas/icsee-ptz/blob/42d04aa3f7ce1d29ea4a64558f0fc53c820e646c/custom_components/icsee_ptz/services.yaml#L44) to -10, or whatever you want. 
* Save and restart home assistant

Don't worry if you don't know how to program, just replace the text as indicated and and you'll be able to test it. If anything breaks, just uninstall and reinstall the component and all the files in the folder will be restored

**Comment by LucaCraft89** [comment]
OMG thank you soo much

**Comment by LucaCraft89** [comment]
hi, @dbuezas i have changeed the line to -10 but i am still getting error

`Failed to call service icsee_ptz/move. value must be at least 0 for dictionary value @ data['preset']`

**Comment by dbuezas** [comment]
Did you restart home assistant?

**Comment by LucaCraft89** [comment]
Yes, I did

**Comment by dbuezas** [comment]
Uhm. I don't know why that could be  maybe delete and read the device?

Btw, you already know -1 doesn't work  have you tried positive numbers?

**Comment by LucaCraft89** [comment]
You mean deleting and adding it again?

And yes but I need it to make the movement stop since the Stop does not work

**Comment by dbuezas** [comment]
Yes, delete and re-add the device

**Comment by LucaCraft89** [comment]
Ok I'll try
