### ISSUE TITLE
Reconfigure camera settings after camera reset ?

### ISSUE THREAD

**Issue by pxFIN** [dbuezas/icsee-ptz#43]
Hello,

Thanks for this addon.. its been tremendous help for using PTZ in camera in home assistant

Maybe i missed from earlier issues/ideas but is it now possible to reconfigure camera settings (like when you first install this addon) without removing and installing again ?.. 

Also in your manifest.json its still 4.0.2 even version should be 4.1.0 ?

**Comment by dbuezas** [comment]
Happy to hear!

> it now possible to reconfigure camera settings (like when you first install this addon)

If you mean things like port and password, then no. That requires a removing and re-adding.


> Also in your manifest.json its still 4.0.2 even version should be 4.1.0 ?

ups...

**Comment by pxFIN** [comment]
Yes i meant i factory resetted due to information from camera manufacturer

But yes.. naturally its best to keep it so integration remove + readd

Got it

**Comment by dbuezas** [comment]
oh, as long as the ip/host, user and pass don't change then you only need to get it connected to the wifi with the manufacturer app. Then HA should reconnect to it

**Comment by pxFIN** [comment]
Of course but i changed it due to manufacturers suggestion and i didnt remember my password thus my issue.. but yes.. i can understand its better to do it via.. reset camera physically+remove + install + remove icsee-ptz install again
