### ISSUE TITLE
System won't start

### ISSUE THREAD

**Issue by Ucsus** [dbuezas/icsee-ptz#5]
Hello! Thank you very much for the integration - I struggled with these cameras without it. I have been waiting for your update with a motion sensor for a long time, yesterday I finally installed it - at first everything was fine, but today for the second time I am faced with the fact that after rebooting the server the system does not boot. It starts to load, but apparently, when it comes to icsee-ptz, something goes wrong - the interface does not open. If you delete the integration folder from custom_components, then everything starts as usual. I installed the integration both through hacs and by copying.

**Comment by dbuezas** [comment]
Oh wow, that's really weird!
I'm using it with 2 cameras continuously and haven't had issues.

Here are some things to try out:
* What do you see in the logs?
* What happens if the integration is installed but you remove all cameras from it?

**Comment by Ucsus** [comment]
I also use two cameras.
Loading without cameras - everything is ok ([log](https://pastebin.com/JgYQZmGc))
It does not load with cameras - preload is spinning, then restarting the system ([log](https://pastebin.com/Vqucz2s5))
Cameras added to generic and go2rtc

**Comment by Ucsus** [comment]
Currently not loading (cameras added). [Here is the log from docker](https://pastebin.com/FbrjfqYa), [here is the log from HA](https://pastebin.com/viUZ9DWz)

**Comment by dbuezas** [comment]
Is adding cameras to this integration the only change?

**Comment by Ucsus** [comment]
Initially, the integration (without movement definition) was installed by copying the repository and the configuration was written in yaml. A couple of days ago I got to the updates - updated HA, esp-home, node-red, adaptive lighting and reinstalled your integration from hacs, deleted the yaml-config, rebooted, added cameras, set up automation - sending photos to telegram by movement and enjoyed life, until I rebooted the server, after that I could not log into the system until I deleted icsee_ptz. Actually, now when adding cameras to the integration, HA takes a long time to load and reboot.

**Comment by dbuezas** [comment]
I see, but you are adding them via the UI, not the yaml, right?

I'll check, I think I may be blocking startup while connecting to the cameras

**Comment by Ucsus** [comment]
Yes, via the UI, via the yaml it will swear.
Thank you! This is the only integration that allows you to control these cameras and does not break them, the only thing it lacked was a motion detector. Through onvif, motioneye and other integrations, the cameras fail, after some time before the power is restarted.

**Comment by dbuezas** [comment]
If you want to try something and give me feedback, you can change this line 
https://github.com/dbuezas/icsee-ptz/blob/50cd12e2bde89c16725d0110add6227fa5713a8d/custom_components/icsee_ptz/binary_sensor.py#L61

And set it to False.

**Comment by Ucsus** [comment]
It seems to work! The cameras have already been added, but the integration folder has been deleted, I added the integration from hacs, changed the line and it started as it should! Now I'm still testing, but everything seems to work. Thanks a lot!

**Comment by dbuezas** [comment]
Ok, then it is what I thought. The only drawback is that the cameras will take 20 seconds to connect after they ara added.
I'll make a new release when I have time :)
Thanks for making the test!

**Comment by dbuezas** [comment]
It will be unavailable right after adding it, so one is not sure if the password and ip are correct for a while. That's what I want to avoid

**Comment by dbuezas** [comment]
Fixed in [v2.0.2](https://github.com/dbuezas/icsee-ptz/releases/tag/v2.0.2)
