### ISSUE TITLE
CPU 100% alarm_worker

### ISSUE THREAD

**Issue by dapuzz** [dbuezas/icsee-ptz#8]
Hi D, sorry to bother you, in your opinion, is it possible that alarm server is blocking in some way the home assistant instance? 
Sometimes, during the day, CPU spikes at 100% and I need to restart the container. 
No evidence inside the logs.

![image](https://github.com/dbuezas/icsee-ptz/assets/45406499/4e6f1735-7468-4046-938c-9e477710c915)
The ps-spy top shows the situation above. Is it correct to have the alarm worker such higher?
If you think this is by design please feel free to delete this issue.

Thanks again
Dario

**Comment by dbuezas** [comment]
Hi!
Very interesting, I don't understand why this could happen. The alarm_worker function is quite simple:
```py
    async def alarm_worker(self):
        while self.socket_writer:
            await self.busy.acquire()
            try:
                (
                    head,
                    version,
                    session,
                    sequence_number,
                    msgid,
                    len_data,
                ) = struct.unpack("BB2xII2xHI", await self.socket_recv(20))
                await asyncio.sleep(0.1)  # Just for receive whole packet
                reply = await self.socket_recv(len_data)
                self.packet_count += 1
                reply = json.loads(reply[:-2])
                if msgid == self.QCODES["AlarmInfo"] and self.session == session:
                    if self.alarm_func is not None:
                        self.alarm_func(reply[reply["Name"]], sequence_number)
            except:
                pass
            finally:
                self.busy.release()

```

**Comment by dbuezas** [comment]
Oh, wait... if the socket is dead, this whole thing becomes a never ending loop

**Comment by dbuezas** [comment]
Is this still occurring for you in the last version?

**Comment by dbuezas** [comment]
I think this just happened to me, and then home assistant restarted itself

**Comment by dbuezas** [comment]
Ok, I can confirm this bug too 
<img width="653" alt="image" src="https://github.com/dbuezas/icsee-ptz/assets/777196/c58b8f5f-9795-4d34-ab67-e388e603dc83">


Commands to see this:
```bash
docker exec -it homeassistant bash
apk add py-spy --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
py-spy top -- python3 -m homeassistant --config /config
```

I'll take a deeper look, this completely crashes home assistant!

**Comment by dbuezas** [comment]
v4.0.2 should fix this. Thanks for reporting this! I didn't know about py-spy, very useful!
